# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hellhtml

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  profile: ${self:custom.profiles.${sls:stage}}
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment: ${file(${opt:stage,self:provider.stage}-hellhtml_env.json)}
  lambdaHashingVersion: 20201221
  variablesResolutionMode: 20210326
  configValidationMode: error
  CheckGitBranchBeforeDeploy:
    staging: master
    production: prod

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-stage-manager
  - check-git-branch-before-deploy
  - serverless-export-env
custom:
  profiles:
    dev: aws-package-user
    staging: default
    prod: default
  stages:
    - dev
    - staging
    - prod
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
    noPrependStageInUrl: false
  customDomain:
    domainName: dev-atlbudgetstudio.studio4510.com
    basepath: dev_hellhtmlAccess