# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hellhtml

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment: ${file(${opt:stage,self:provider.stage}-hellhtml_env.json)}
  lambdaHashingVersion: 20201221
  variablesResolutionMode: 20210326
  configValidationMode: error

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-domain-manager
custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
    noPrependStageInUrl: fales
  customDomain:
    domainName: dev-atlbudgetstudio.studio4510.com
    basepath: dev_hellhtml
